sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run --rm -w /scripts -v $(pwd):/scripts koalaman/shellcheck -x
   kubler.sh lib/*.sh engine/{docker,podman}.sh engine/docker/bob-core/*.sh cmd/*.sh cmd/argbash/argbash-refresh.sh
